export {default as Home} from "./Home/Home.tsx"
export {default as Login} from "./Login/Login.tsx"
export {default as Other} from "./Other/Other.tsx"
export {default as About} from "./About/About.tsx"
export {default as SignIn} from "./SignIn/SignIn.tsx"